# Generated by Django 5.1.1 on 2025-04-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_rename_career_quizquestion_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='subject',
            field=models.CharField(choices=[('Python', 'Python'), ('Web Development', 'Web Development'), ('Soft Skills', 'Soft Skills')], max_length=100),
        ),
    ]
